Bug: ['**/bugfix/**', '**/bug/**']
Driver: ['all/**', 'driver/**', '*_driver-*']
Hotfix: '**/hotfix/**'
Localization: 'translations_*'
Passenger: ['all/**', 'passenger/**', '*_passenger-*']
Release: '**/release/**'
Sandbox: 'sandbox/**'
