package com.example.testlabels

import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }

    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines//add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines
    //    //add lines


    override fun onStart() {
        super.onStart()
    }

}
