package com.example.testlabels

import android.content.Intent
import android.content.ServiceConnection
import android.os.Bundle
import androidx.appcompat.app.AppCompatActivity
import java.util.concurrent.Executor

class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)
    }

    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines
    //add lines


    override fun bindIsolatedService(
        service: Intent,
        flags: Int,
        instanceName: String,
        executor: Executor,
        conn: ServiceConnection
    ): Boolean {
        return super.bindIsolatedService(service, flags, instanceName, executor, conn)
    }
}
