name: Optimus PRime

on:
  pull_request:
    types: [opened, closed, ready_for_review, reopened]

jobs:
  # Add the pull request creator as assignee
  add-assignee:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to creator
        if: ${{ github.event.action == 'opened' }}
        uses: thomaseizinger/assign-pr-creator-action@v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

  # Add labels based on branch name
  add-branch-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Add branch name labels
        if: ${{ github.event.action == 'opened' }}
        uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pull-request-labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Add pull request status-indicating labels
  add-status-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Clear status label
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{github.token}}
          script: |
            const prLabels = await github.issues.listLabelsOnIssue({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number
            })
            if (prLabels.data.find(element => element.name == 'Ready for Review')) {
              github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                name: 'Ready for Review'
              })
            } else if (prLabels.data.find(element => element.name == 'WIP')) {
              github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                name: 'WIP'
               })
            } else if (prLabels.data.find(element => element.name == 'Ready')) {
              github.issues.removeLabel({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 issue_number: context.payload.number,
                 name: 'Ready'
               })
            } else if(prLabels.data.find(element => element.name == 'Declined')) {
              github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.number,
                name: 'Declined'
              })
            }
      - name: Add Ready for Review label
        if: ${{ (github.event.action == 'opened' || github.event.action == 'ready_for_review' || github.event.action == 'reopened') && !github.event.pull_request.draft }}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              labels: ['Ready for Review']
            })
      - name: Add WIP label
        if: ${{ github.event.action == 'opened' && github.event.pull_request.draft }}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              labels: ['WIP']
            })
      - name: Add Ready label
        if: ${{ github.event.action == 'closed' && github.event.pull_request.merged}}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              labels: ['Ready']
            })
      - name: Add Declined label
        if: ${{ github.event.action == 'closed' && !github.event.pull_request.merged}}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{github.token}}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.number,
              labels: ['Declined']
            })
